# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Restaurant' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'SQLite.swift', '~> 0.12.0'
  # Pods for Restaurant

  target 'RestaurantTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RestaurantUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
